In [1]:
#importing the libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
datasets=pd.read_csv("Social_Network_Ads.csv")

In [3]:
datasets.head(133)

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
128  15722758    Male   30            17000          0
129  15792102  Female   26            84000          0
130  15675185    Male   31            58000          0
131  15801247    Male   33            31000          0
132  15725660    Male   30            87000          0

[133 rows x 5 columns]

In [4]:
datasets=pd.get_dummies(datasets,drop_first=True)

In [5]:
datasets

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [6]:
indep=datasets[['Age', 'EstimatedSalary','Gender_Male']]
dep=datasets['Purchased']

In [7]:
indep

Age  EstimatedSalary  Gender_Male
0     19            19000            1
1     35            20000            1
2     26            43000            0
3     27            57000            0
4     19            76000            1
..   ...              ...          ...
395   46            41000            0
396   51            23000            1
397   50            20000            0
398   36            33000            1
399   49            36000            0

[400 rows x 3 columns]

In [8]:
dep

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(indep,dep,test_size=0.30,random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
from sklearn.ensemble import RandomForestClassifier

In [12]:
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion':['gini','entropy'],
              'max_features': ['auto','sqrt','log2'],
              'n_estimators':[10,100]} 





grid = GridSearchCV(RandomForestClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
# fitting the model for grid search 
grid.fit(X_train, y_train) 
 


Fitting 5 folds for each of 12 candidates, totalling 60 fits


GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             scoring='f1_weighted', verbose=3)

In [13]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)



In [14]:

from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)


The f1_macro value for best parameter {'criterion': 'gini', 'max_features': 'auto', 'n_estimators': 100}: 0.9171245421245421


In [15]:
from sklearn.metrics import accuracy_score
accuracy_score=accuracy_score(y_test,grid_predictions)
print("The accuracy_score value for best parameter {}:".format(grid.best_params_),accuracy_score)

The accuracy_score value for best parameter {'criterion': 'gini', 'max_features': 'auto', 'n_estimators': 100}: 0.9166666666666666


In [16]:
from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score=balanced_accuracy_score(y_test,grid_predictions)
print("The balanced_accuracy_score for best parameter {}:".format(grid.best_params_),balanced_accuracy_score)


The balanced_accuracy_score for best parameter {'criterion': 'gini', 'max_features': 'auto', 'n_estimators': 100}: 0.9132448286508181


In [17]:
from sklearn.metrics import top_k_accuracy_score
top_k_accuracy_score=top_k_accuracy_score(y_test, grid_predictions, k=2)
print("The top_k_accuracy_score for best parameter {}:".format(grid.best_params_),top_k_accuracy_score)


The top_k_accuracy_score for best parameter {'criterion': 'gini', 'max_features': 'auto', 'n_estimators': 100}: 1.0


C:\Users\rajah\anaconda3\envs\pugazh\lib\site-packages\sklearn\metrics\_ranking.py:1745: UndefinedMetricWarning: 'k' (2) greater than or equal to 'n_classes' (2) will result in a perfect score and is therefore meaningless.
  UndefinedMetricWarning,


In [18]:
from sklearn.metrics import average_precision_score
average_precision_score=average_precision_score(y_test, grid_predictions)
print("The average_precision_score value for best parameter {}:".format(grid.best_params_),average_precision_score)


The average_precision_score value for best parameter {'criterion': 'gini', 'max_features': 'auto', 'n_estimators': 100}: 0.8098506333900548


In [19]:
from sklearn.metrics import brier_score_loss
brier_score_loss=brier_score_loss(y_test, grid_predictions)
print("The brier_score_loss for best parameter {}:".format(grid.best_params_),brier_score_loss)


The brier_score_loss for best parameter {'criterion': 'gini', 'max_features': 'auto', 'n_estimators': 100}: 0.08333333333333333


In [20]:
from sklearn.metrics import log_loss
log_loss=log_loss(y_test,grid_predictions)
print("The log_loss for best parameter {}:".format(grid.best_params_),log_loss)


The log_loss for best parameter {'criterion': 'gini', 'max_features': 'auto', 'n_estimators': 100}: 2.8782713461140674


In [21]:
from sklearn.metrics import precision_score
precision_score=precision_score(y_test,grid_predictions,average='weighted')
print("The precision_score for best parameter {}:".format(grid.best_params_),precision_score)


The precision_score for best parameter {'criterion': 'gini', 'max_features': 'auto', 'n_estimators': 100}: 0.9181264471962147


In [22]:
from sklearn.metrics import recall_score
recall_score=recall_score(y_test,grid_predictions)
print("The recall_score for best parameter {}:".format(grid.best_params_),recall_score)


The recall_score for best parameter {'criterion': 'gini', 'max_features': 'auto', 'n_estimators': 100}: 0.9024390243902439


In [23]:
from sklearn.metrics import jaccard_score
jaccard_score=jaccard_score(y_test,grid_predictions,average=None)
print("The jaccard_score for best parameter {}:".format(grid.best_params_),jaccard_score)


The jaccard_score for best parameter {'criterion': 'gini', 'max_features': 'auto', 'n_estimators': 100}: [0.87951807 0.78723404]


In [24]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[73  6]
 [ 4 37]]


In [25]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.95      0.92      0.94        79
           1       0.86      0.90      0.88        41

    accuracy                           0.92       120
   macro avg       0.90      0.91      0.91       120
weighted avg       0.92      0.92      0.92       120



In [26]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.9648039518369868

In [27]:
print(grid.best_params_)

{'criterion': 'gini', 'max_features': 'auto', 'n_estimators': 100}


In [28]:
table=pd.DataFrame.from_dict(re)

In [29]:
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.042355      0.010288         0.006401    3.200579e-03   
1        0.372885      0.014454         0.027972    4.512745e-03   
2        0.034677      0.004170         0.009375    4.329651e-03   
3        0.352384      0.021414         0.028426    8.166075e-03   
4        0.028220      0.006300         0.006250    7.655006e-03   
5        0.339149      0.032728         0.024000    8.971638e-07   
6        0.034821      0.012631         0.007927    4.943411e-03   
7        0.302401      0.018521         0.024001    2.328216e-06   
8        0.032000      0.005059         0.011200    8.158270e-03   
9        0.328001      0.021467         0.030401    5.985810e-03   
10       0.036795      0.006401         0.014410    1.377445e-02   
11       0.303428      0.030264         0.019436    4.189301e-03   

   param_criterion param_max_features param_n_estimators  \
0             gini               auto                 10   
1             gini               auto                100   
2             gini               sqrt                 10   
3             gini               sqrt                100   
4             gini               log2                 10   
5             gini               log2                100   
6          entropy               auto                 10   
7          entropy               auto                100   
8          entropy               sqrt                 10   
9          entropy               sqrt                100   
10         entropy               log2                 10   
11         entropy               log2                100   

                                               params  split0_test_score  \
0   {'criterion': 'gini', 'max_features': 'auto', ...           0.855314   
1   {'criterion': 'gini', 'max_features': 'auto', ...           0.874254   
2   {'criterion': 'gini', 'max_features': 'sqrt', ...           0.892857   
3   {'criterion': 'gini', 'max_features': 'sqrt', ...           0.874254   
4   {'criterion': 'gini', 'max_features': 'log2', ...           0.855314   
5   {'criterion': 'gini', 'max_features': 'log2', ...           0.874254   
6   {'criterion': 'entropy', 'max_features': 'auto...           0.855314   
7   {'criterion': 'entropy', 'max_features': 'auto...           0.874254   
8   {'criterion': 'entropy', 'max_features': 'sqrt...           0.855314   
9   {'criterion': 'entropy', 'max_features': 'sqrt...           0.874254   
10  {'criterion': 'entropy', 'max_features': 'log2...           0.892857   
11  {'criterion': 'entropy', 'max_features': 'log2...           0.874254   

    split1_test_score  split2_test_score  split3_test_score  \
0            0.876643           0.823129           0.929144   
1            0.875644           0.859435           0.911105   
2            0.838326           0.859435           0.875548   
3            0.838326           0.841398           0.911105   
4            0.802399           0.804584           0.892857   
5            0.821429           0.823129           0.911105   
6            0.838326           0.804584           0.874356   
7            0.821429           0.841398           0.911105   
8            0.802399           0.823129           0.911105   
9            0.857143           0.823129           0.911105   
10           0.802399           0.821429           0.911105   
11           0.857143           0.841398           0.929144   

    split4_test_score  mean_test_score  std_test_score  rank_test_score  
0            0.907658         0.878378        0.037475                6  
1            0.945469         0.893181        0.031177                1  
2            0.909115         0.875056        0.024780                8  
3            0.927778         0.878572        0.036055                5  
4            0.870721         0.845175        0.036073               12  
5            0.946153         0.875214        0.048841                7  
6          

In [30]:
table_pr=pd.DataFrame()

In [31]:
print(X_test)

[[-0.77101313  0.49720103  0.99288247]
 [ 0.0133054  -0.57280368 -1.00716855]
 [-0.28081405  0.15017248  0.99288247]
 [-0.77101313  0.26584866 -1.00716855]
 [-0.28081405 -0.57280368 -1.00716855]
 [-1.06513258 -1.44037507  0.99288247]
 [-0.67297331 -1.5849703  -1.00716855]
 [-0.18277423  2.14558666  0.99288247]
 [-1.94749093 -0.05226085 -1.00716855]
 [ 0.89566375 -0.775237    0.99288247]
 [-0.77101313 -0.60172273  0.99288247]
 [-0.96709276 -0.42820845 -1.00716855]
 [-0.08473441 -0.42820845  0.99288247]
 [ 0.11134522  0.20801057  0.99288247]
 [-1.7514113   0.46828198  0.99288247]
 [-0.5749335   1.36477242 -1.00716855]
 [-0.08473441  0.20801057  0.99288247]
 [-1.84945111  0.43936294  0.99288247]
 [ 1.67998229  1.74072002 -1.00716855]
 [-0.28081405 -1.38253697  0.99288247]
 [-0.28081405 -0.65956082 -1.00716855]
 [ 0.89566375  2.14558666 -1.00716855]
 [ 0.30742485 -0.54388463 -1.00716855]
 [ 0.89566375  1.01774386  0.99288247]
 [-1.45729185 -1.2090227  -1.00716855]
 [ 1.09174339  2.05882953